[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
entity-registry = "6fEr9VsnyCUdCPMHY7XYV6SFsw7td48aN9biM1UowzGh"
pooling-engine = "Cot9BDy1Aos6fga3D7ZcaYmzdXxqAJ4jHFGMHDdbq8Sz"
compliance-hook = "5rogVdJwxrCGBVPEKV42aeKxwpnW4ESQbccpMbN2BPNS"
fx-netting = "2RfkQCsFUjtzX1PavSHF2ZgCQj9Ua1Q72pLAzd3KfnZ7"
sweep-trigger = "4EbB5Ahei4nhAkfrqyjr7ZE3VPyBhi4pbMRyrpyRbEQq"

[programs.localnet]
entity-registry = "6fEr9VsnyCUdCPMHY7XYV6SFsw7td48aN9biM1UowzGh"
pooling-engine = "Cot9BDy1Aos6fga3D7ZcaYmzdXxqAJ4jHFGMHDdbq8Sz"
compliance-hook = "5rogVdJwxrCGBVPEKV42aeKxwpnW4ESQbccpMbN2BPNS"
fx-netting = "2RfkQCsFUjtzX1PavSHF2ZgCQj9Ua1Q72pLAzd3KfnZ7"
sweep-trigger = "4EbB5Ahei4nhAkfrqyjr7ZE3VPyBhi4pbMRyrpyRbEQq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
